### ISSUE TITLE
C language support

### ISSUE THREAD

**Issue by Gen1Code** [twibiral/obsidian-execute-code#163]
Saw that C# and C++ was supported
Why not C?

**Comment by chlohal** [comment]
I think it's just because nobody's suggested it :) Would you like C support?

**Comment by Gen1Code** [comment]
yep, would be very handy to be able to run my code instead of just showing it

**Comment by milan338** [comment]
We could implement this by passing C code to cling like with C++, just wrapping the code in an `extern "C"` block. Since it would basically be the same executor as C++, it might make sense to change the settings to be C/C++ settings, and then use the same C++ executor, only adding an additional check if the language is C to wrap the code.

**Comment by chlohal** [comment]
I was thinking the same thing re: cling! I didn't know about `extern "C"`, though; thanks, Milan. 

I'm not sure about making the settings the same. It makes sense, IMO, to use the same executor on the backend, but we might want to provide a separate settings interface so that the display-name for CPP doesn't need to be change. 

Right now, display names are implemented by a map; we could also change it to be a function which requires `languageId` and context (`: "settings" | "executor-manager" | ...`).

**Comment by milan338** [comment]
I think you're right actually, having separate settings would be better. Though thinking about it, with using the same executor, this might get a bit messy with having to pass down extra params, it might just be easiest to have a C executor inherit from the C++ one and override the run method. It's not the greatest approach semantically, but I think it'll lead to a cleaner implementation. Let me know what you think.

Another thought, with wrapping the code in an extern block, errors might show up on different lines in the code block output than what the user would expect, and come to think of it, this is an issue with all global / pre / post injections e.g. if there's an error on line 1 of the global inject, the code block error output will show something like 'error on line 1', but to the user this won't make sense since line 1 of the actual code block they're running is completely different (since they don't see the final transformed code with injects added). I'm not sure how this could be fixed, one approach would require a per-language implementation to scan for errors and add our own message like '(in global inject)'. Not sure how worthwhile this would be though.

**Comment by twibiral** [comment]
I was thinking about adding C when the plugin was relatively new. The easiest way would be to use clang, I guess. But I was also considering compiling the C programs to [WebAssembly](https://webassembly.org/). This way it's more OS-independent and doesn't require the installation of a compiler (which simplifies the use of C for beginners).

@chlohal and @milan338 When using clang inheriting from the C++ and making separate settings sounds good!

@milan338 you're right, the line numbering is a problem! I created issue #164 for this.

**Comment by twibiral** [comment]
Released in [1.5.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.5.0) :)
