### ISSUE TITLE
Run in Live Preview

### ISSUE THREAD

**Issue by rmchale** [twibiral/obsidian-execute-code#17]
Would it be possible to run in preview?

**Comment by twibiral** [comment]
Probably yes, but probably not with a button. One possibility would be to execute the code block where the cursor currently is when a key shortcut is activated.

**Comment by twibiral** [comment]
That would probably work

**Comment by twibiral** [comment]
The changes in #20  don't really do anything?

I don't like this because writing "run-" before the name of the language removes the syntax highlighting and the plugin wont be plug-and-play anymore if you have to change all your existing code blocks to use it.

**Comment by twibiral** [comment]
Yeah, that looks great, but the rendering doesn't work if the Jupyter Plugin isn't enabled. 

If you disable the Jupyter Plugin and try your changes, the code blocks don't get rendered in the Preview.

**Comment by twibiral** [comment]
I don't no what went wrong but now it works. 

Do you know a way to fix the layout changes that appear when using `run-lang` instead of `lang`?


> I did find a rendering issue if the document is left open when you close obsidian and reopen. There was a simple fix for that. Shall I submit a new pr?

Yeah that would be best. Maybe merge the new changes in develop into your code base beforehand.

It would be great if we find a solution to above mentioned problem before creating a new pr

**Comment by twibiral** [comment]
Solved by pull request #25
