### ISSUE TITLE
[FR] button to open contents of code block in code editor

### ISSUE THREAD

**Issue by erauner12** [twibiral/obsidian-execute-code#194]
If I want to make changes to the code with the full power of a code editor, it would be cool if I could open the contents of the code in an individual block in vscode, for example.

**Comment by erauner12** [comment]
if `run-javascript` for example, then open open in vscode with syntax highlighting of `.js` file:

ex:

```javascript
function multiple(x) {

    function fn(y)
    {
        return x * y;
    }
    
    return fn;
}

var triple = multiple(3);
triple(2); // returns 6
triple(3); // returns 9
console.log(triple(2));
```

**Comment by chlohal** [comment]
Would this open the Markdown file, but with JS language mode on? Or a separate file created for the specific code block?

**Comment by chlohal** [comment]
I see, thanks. Currently, editing the code block content is difficult for the plugin (as we apply buttons to the *rendered* version -- accessing the source code from the rendered version is hard).

This can definitely be done, but we'd have to get that working first. Thanks!

**Comment by twibiral** [comment]
As @chlohal said, this is hard to do and not part of the near-future roadmap. If you use `javascript` instead of `run-javascript` at least the syntax highlighting will still work and you can still run the code in the reading. You can also install the plugin [Completr](https://github.com/tth05/obsidian-completr) to get an IDE-like auto-completion.

**Comment by erauner12** [comment]
Makes sense, I appreciate the consideration!
