### ISSUE TITLE
Add support for Standard ML 

### ISSUE THREAD

**Issue by sbhal** [twibiral/obsidian-execute-code#306]
Can we please add support for Standard ML using SML/NJ interpreter?
https://www.smlnj.org/

**Comment by twibiral** [comment]
Hi! I have never heard of that language. You can look at [this PR](https://github.com/twibiral/obsidian-execute-code/pull/265) if you want to implement it yourself. Otherwise I need more info on the language:

- [ ] A typical code snippet I can run
- [ ] The command to run the snippet (and a short explanation of any arguments, if necessary)
- [ ] File Ending (like .py for Python)

Any other things I need to know?
