### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by pspiagicw** [twibiral/obsidian-execute-code#48]
Java support is in the future plans. From what I can gather JDK11 and after, support running single file programs without the intermediate compiling step.
Source: https://www.infoq.com/articles/single-file-execution-java11/

I have personally tested and confirmed the above article.
It means a single-file java program can be run using `java program.java` .
But this means
- We have locked the user to use JDK11 and higher.

Can we use it ? If yes implementing it is easy.

**Comment by twibiral** [comment]
I was thinking about Jshell (which works since Java 9, I think) but your solution is much easier.

I think it's reasonable to only allow Java 11 or higher as Java 11 can execute all older programs too and most people using Java have it installed anyways.

Another question is the use of libraries. I think there is know way to make external libraries accessible.

**Comment by twibiral** [comment]
Released in #50
