### ISSUE TITLE
[FR] Reuse code blocks defined above

### ISSUE THREAD

**Issue by milan338** [twibiral/obsidian-execute-code#56]
When writing in a document, it might be helpful to be able to define some functions in code blocks above, then use them later in code blocks below, kind of like Jupyter notebooks. I'm working on a prototype, it looks like this right now:

![image](https://user-images.githubusercontent.com/56327606/190675425-2a6a9460-eb13-4718-8553-27a62965aa89.png)

Right now, it works by making a distinction between 'runnable' and 'non-runnable' code blocks, where runnable code blocks have a main function defined. You can toggle the feature in the settings per-language, and when enabled, it prevents running code blocks without a main function, and those code blocks are instead prepended to any runnable code blocks. It will also only prepend any code blocks above the one being run. I'd like to get some feedback on this idea to see how it can be developed further.

As a consequence of how the feature is implemented, it should be trivial to implement both solutions proposed by by @twibiral in https://github.com/twibiral/obsidian-execute-code/issues/22#issuecomment-1249279875 and close #22, however the pre and post scripts would be restricted to the note they are defined in.

**Comment by twibiral** [comment]
If we implement it this way we have to implement it for each supported language separately. And one has to write a main function for each block of course that one wants to execute.

I prefer to just put some lines of say python into the block and have it executed.

It's easier for the user if they must only change the `js` to `pre-js` and have this executed before each block. Implemented this way it works for all languages at once without the need to code it separately for each language.

This kind of prefix works great with obsidian, it is already utilized by this plugin to render and execute code in the live preview. (See #17)

**Comment by milan338** [comment]
I agree the prefix idea is a lot better. Maybe we need a way to opt-out of this behaviour per code block when needed, could be something as simple as chaining together prefixes like `nopre-nopost-noinject-python` to be able to disable pre, post, or global injection?

**Comment by twibiral** [comment]
I agree that the best solution is probably to apply pre/post blocks only to the blocks below. This gives higher control about which blocks are used just by ordering them and doesn't need extra code words. I think it's also very intuitive.

I think we don't need an opt-out mechanism for the pre/post blocks. They are included if pre/post is set, otherwise, this is ignored and they are handled as normal code blocks.

I created the new [ReuseBlocks](/twibiral/obsidian-execute-code/tree/feature/ReuseBlocks) branch to work on this and merge new pull requests into. I will start to try to implement the rendering of pre/post blocks to ensure they are still rendered as a code block with the respective language instead of code blocks with an unknown language.

**Comment by milan338** [comment]
Sounds good, I've got most of the functionality down from the prototype, just need to restrict it to pre / post blocks, should have a PR soon. What are your thoughts on the global code injection? I think it's still important for repetitive things like imports, we could have a dropdown in the settings for per-language configuration.

**Comment by twibiral** [comment]
Okay, I am curious to see how you implemented it.

Your right, global code injection would be great!

**Comment by twibiral** [comment]
Solved in [0.15.0](https://github.com/twibiral/obsidian-execute-code/releases/tag/0.15.0).
